name: 📝 Rule Contribution
description: I have a rule to contribute
title: "[CONTRIBUTION] "
labels: ["contribution", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing! Please provide details about your rule.
  
  - type: input
    id: rule-name
    attributes:
      label: Rule Name
      description: What should this rule file be called?
      placeholder: e.g., golang-standards.mdc
    validations:
      required: true
  
  - type: input
    id: language
    attributes:
      label: Language/Framework
      description: What language or framework does this rule cover?
      placeholder: e.g., Go, Rust, Vue.js
    validations:
      required: true
  
  - type: textarea
    id: rule-content
    attributes:
      label: Rule Content
      description: Paste your complete rule file here (including frontmatter)
      render: markdown
      placeholder: |
        ---
        description: Your rule description
        globs: **/*.ext
        alwaysApply: false
        ---
        
        # Rule Title
        
        Your rule content...
    validations:
      required: true
  
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why are these the best practices for this language/framework?
      placeholder: These patterns are recommended because...
    validations:
      required: true
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Contribution Checklist
      description: Please confirm you've completed these steps
      options:
        - label: Rule is under 500 lines
          required: true
        - label: Includes concrete examples (✅ GOOD / ❌ BAD patterns)
          required: true
        - label: Frontmatter is complete and correct
          required: true
        - label: Tested in a real project
          required: true
        - label: Follows the format of existing rules
          required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Notes
      description: Any other information about your contribution
